const cardData = [
	{
		id: 1,
		img: '/extrawide.png',
		title: 'Art Title',
		price: 100,
		description:
			'Enjoy shopping with our exclusive offer free shipping on all purchase over $1000 so hurry to take advantage of the offer.',
		categories: ['Abstract', 'Modern'],
		roomTypes: ['Fitness', 'Living'],
		designer: 'John Doe',
		artist: null,
		primaryColors: ['FF5733', '33FF57', '3357FF'],
		stock: 50,
		sizesAvailable: 'extra wide',
	},
	{
		id: 2,
		img: 'https://img.freepik.com/free-vector/sunset-sunrise-ocean-nature-landscape_33099-2244.jpg',
		price: 100,
		title: 'Art Title',
		description:
			'Enjoy shopping with our exclusive offer free shipping on all purchase over $1000 so hurry to take advantage of the offer.',
		categories: ['Abstract', 'Modern'],
		roomTypes: ['Bedroom'],
		designer: 'John Doe',
		artist: null,
		primaryColors: ['3358FF', 'FF3333', 'F0FF33'],
		stock: 50,
		sizesAvailable: 'landscape',
	},
	{
		id: 3,
		img: '/painting.png',
		price: 100,
		title: 'Art Title',
		description:
			'Enjoy shopping with our exclusive offer free shipping on all purchase over $1000 so hurry to take advantage of the offer.',
		categories: ['Abstract', 'Modern'],
		roomTypes: ['Living', 'Bedroom'],
		designer: 'Jack',
		artist: null,
		primaryColors: ['3358FF', 'FF3333', 'F0FF33'],
		stock: 50,
		sizesAvailable: 'portrait',
	},
	{
		id: 4,
		img: '/wallart.png',
		price: 100,
		title: 'Art Title',
		description:
			'Enjoy shopping with our exclusive offer free shipping on all purchase over $1000 so hurry to take advantage of the offer.',
		categories: ['Abstract', 'Modern'],
		roomTypes: ['Living', 'Fitness'],
		designer: 'John Doe',
		artist: null,
		primaryColors: ['3358FF', 'FF3333', 'FFC5EA'],
		stock: 50,
		sizesAvailable: 'landscape',
	},
	{
		id: 5,
		img: '/painting.png',
		title: 'Entrance Elegance',
		price: 100,
		description: 'A modern take on abstract art, perfect for a grand entrance.',
		categories: ['Abstract', 'Animals'],
		roomTypes: ['Entrance'],
		designer: 'John Doe',
		artist: 'null',
		primaryColors: ['FF5733', 'D1E8E2', '33FF57', '3357FF'],
		stock: 50,
		sizesAvailable: 'portrait',
	},
	{
		id: 6,
		img: '/wallart.png',
		title: 'Wild Lobby',
		price: 120,
		description:
			'Experience the wilderness from the comfort of your lobby with this animal-themed masterpiece.',
		categories: ['Animals'],
		roomTypes: ['Lobby'],
		designer: 'Julius',
		artist: 'Jane Smith',
		primaryColors: ['3358FF', 'FF3333', 'F0FF33'],
		stock: 30,
		sizesAvailable: 'landscape',
	},
	{
		id: 7,
		img: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61',
		title: 'Corridor Calmness',
		price: 140,
		description:
			'An architectural art piece that brings serenity to your corridors.',
		categories: ['Architectural'],
		roomTypes: ['Corridor'],
		designer: 'Alice',
		artist: 'Bob Smith',
		primaryColors: ['D1E8E2', 'FFC3A0', 'FF5733'],
		stock: 40,
		sizesAvailable: 'landscape',
	},
	{
		id: 8,
		img: '/wallart.png',
		title: 'Elevator Escapade',
		price: 110,
		description: 'A cartoonish delight to lighten up your elevator lobby!',
		categories: ['Cartoon'],
		roomTypes: ['Elevator Lobby'],
		designer: 'Charlie',
		artist: 'David',
		primaryColors: ['FFC3A0', 'D1E8E2', 'FF5733'],
		stock: 45,
		sizesAvailable: 'landscape',
	},
	{
		id: 9,
		img: '/wallart.png',
		title: 'Fitness Finesse',
		price: 130,
		description: 'A creative blend of colors to motivate your fitness routines.',
		categories: ['Creative'],
		roomTypes: ['Fitness'],
		designer: 'Eva',
		artist: 'Frank',
		primaryColors: ['D1E8E2', 'FFC3A0', 'FF5733'],
		stock: 35,
		sizesAvailable: 'landscape',
	},
];
export default cardData;
